version: '3'

services:

  mariadb:
    image: mariadb:10.5.6
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=tp2
      - MYSQL_ROOT_PASSWORD=EsH0rr1BL3.q.Esto.Este.ACAA
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/mariadb/var/lib/mysql:/var/lib/mysql
    ports:
      - "4000:3306"

  webapp:
    image: webapp:tp2-1.0
    build:
      context: webapp
    container_name: webapp
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWD=EsH0rr1BL3.q.Esto.Este.ACAA
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/webapp/app:/app:ro
    ports:
      - "8081:5000"
    depends_on:
      - mariadb
